field.formatter.settings.slugify:
  type: mapping
  label: 'Converts into a slug formatter settings'
  mapping:
    separator:
      type: string
      label: 'Text Separator'

field.formatter.settings.tooltip:
  type: mapping
  label: 'Show tooltip on hover formatter settings'
  mapping:
    separator:
      type: string
      label: 'Tooltip on hover'

